=== jrlmx/sourdough/config-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://jrlmx.com/projects/sourdough/config-schema.json",
    "title": "sourdough config",
    "description": "a sourdough 'starter' configuration file for specifying project dependencies, commands to run, and files to be removed when scaffolding a new project",
    "type": "object",
    "properties": {
        "git_url": {
            "type": "string",
            "title": "git url",
            "description": "url of a git repo to clone instead of using the Laravel installer"
        },
        "flags": {
            "type": "array",
            "title": "flags",
            "description": "list of flags to pass to the Laravel installer",
            "items": {
                "type": "string"
            }
        },
        "php": {
            "type": "object",
            "title": "composer dependencies",
            "properties": {
                "prod": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "list of composer packages to install for production"
                },
                "dev": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "list of composer packages to install for development"
                },
                "remove": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "list of composer packages to remove when scaffolding a new project"
                }
            }
        },
        "js": {
            "type": "object",
            "title": "npm dependencies",
            "properties": {
                "prod": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "list of npm packages to install for production"
                },
                "dev": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "list of npm packages to install for development"
                },
                "remove": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "list of npm packages to remove when scaffolding a new project"
                }
            }
        },
        "repos": {
            "type": "array",
            "title": "composer repositories",
            "description": "list of composer repositories to install before scaffolding a new project",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    },
                    "auth": {
                        "type": "boolean"
                    }
                },
                "required": ["name", "url"]
            }
        },
        "artisan": {
            "type": "array",
            "title": "artisan commands",
            "description": "list of artisan commands to run when scaffolding a new project",
            "items": {
                "type": "string"
            }
        },
        "npx": {
            "type": "array",
            "title": "npx commands",
            "description": "list of npx commands to run when scaffolding a new project",
            "items": {
                "type": "string"
            }
        },
        "commands": {
            "type": "array",
            "title": "custom commands",
            "description": "list of user defined commands to run when scaffolding is complete - whitelisted: npm, npx, php, composer, git, and anything in the /vendor or /node_modules folder(s)",
            "items": {
                "type": "string"
            }
        },
        "remove_files": {
            "type": "array",
            "title": "files to remove",
            "description": "list of default files to remove when scaffolding a new project - e.g /resources/views/welcome.blade.php",
            "items": {
                "type": "string"
            }
        }
    }
}

=== jrlmx/sourdough/starters/inertia_svelte/config.json
{
    "php": {
        "prod": ["inertiajs/inertia-laravel"],
        "dev": [],
        "remove": []
    },
    "js": {
        "prod": [],
        "dev": [
            "prettier",
            "prettier-plugin-blade",
            "prettier-plugin-svelte",
            "prettier-plugin-tailwindcss",
            "svelte@latest",
            "@inertiajs/svelte",
            "@sveltejs/vite-plugin-svelte",
            "@tailwindcss/forms",
            "@tailwindcss/typography"
        ],
        "remove": []
    },
    "artisan": ["inertia:middleware"],
    "remove_files": ["resources/views/welcome.blade.php"]
}

=== jrlmx/sourdough/kits/flux/config.json
{
    "php": {
        "prod": ["laravel/folio", "livewire/livewire", "livewire/volt", "livewire/flux", "livewire/flux-pro"],
        "dev": [],
        "remove": []
    },
    "js": {
        "prod": [],
        "dev": ["prettier", "prettier-plugin-blade", "@tailwindcss/typography"],
        "remove": []
    },
    "repos": [
        {
            "name": "flux-pro",
            "url": "composer.fluxui.dev",
            "auth": true
        }
    ],
    "artisan": ["folio:install", "volt:install"],
    "remove_files": ["resources/views/welcome.blade.php"]
}

=== jrlmx/sourdough/starters/react-shadcn/config.json
{
    "$schema": "../../config-schema.json",
    "php": {
        "prod": [],
        "dev": ["laravel/breeze"],
        "remove": []
    },
    "js": {
        "prod": [],
        "dev": [],
        "remove": []
    },
    "artisan": ["breeze:install react --typescript --no-interaction"],
    "npx": ["shadcn@latest init"],
    "repos": [],
    "remove_files": []
}

=== jrlmx/sourdough/kits/inertia_svelte/config.json
{
    "php": {
        "prod": ["inertiajs/inertia-laravel"],
        "dev": [],
        "remove": []
    },
    "js": {
        "prod": [],
        "dev": [
            "prettier",
            "prettier-plugin-blade",
            "prettier-plugin-svelte",
            "prettier-plugin-tailwindcss",
            "@inertiajs/svelte",
            "svelte@latest",
            "@sveltejs/vite-plugin-svelte",
            "@tailwindcss/forms",
            "@tailwindcss/typography"
        ],
        "remove": []
    },
    "artisan": ["inertia:middleware"],
    "remove_files": ["resources/views/welcome.blade.php"]
}

=== jrlmx/sourdough/starters/flux/config.json
{
    "php": {
        "prod": ["laravel/folio", "livewire/livewire", "livewire/volt", "livewire/flux", "livewire/flux-pro"],
        "dev": ["wire-elements/wire-spy"]
    },
    "js": {
        "dev": ["prettier", "prettier-plugin-blade", "@tailwindcss/typography"]
    },
    "repos": [
        {
            "name": "flux-pro",
            "url": "composer.fluxui.dev",
            "auth": true
        }
    ],
    "artisan": ["folio:install", "volt:install"],
    "commands": ["interact:git init"],
    "remove_files": ["resources/views/welcome.blade.php"]
}

=== jrlmx/sourdough/starters/example/config.json
{
    "$schema": "../../config-schema.json",
    "remove_files": ["resources/views/welcome.blade.php", "resources/js/bootstrap.js"],
    "repos": [],
    "php": {
        "prod": ["livewire/livewire", "livewire/volt", "laravel/folio"],
        "dev": ["wire-elements/wire-spy"],
        "remove": []
    },
    "js": {
        "prod": [],
        "dev": ["prettier", "prettier-plugin-blade", "@tailwindcss/typography", "@tailwindcss/forms"],
        "remove": ["axios"]
    },
    "artisan": ["folio:install", "volt:install"],
    "npx": [],
    "commands": ["git init", "git add .", "quiet:git commit -m \"initial\"", "quiet:./vendor/bin/pint"]
}
